[project]
name = "public-hub-services"
version = "0.1.1"
description = "Microservice to provide open functionality for the biocentral hub server"
authors = [
    {name = "Sebastian", email = "sebastian.franz@tum.de"}
]
license = {text = "GPLv3"}
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "redis>=5.2.1",
    "fastapi>=0.119.0",
    "uvicorn>=0.37.0",
    "email-validator>=2.3.0",
    "requests>=2.32.5",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["public_hub_services"]
